root: true

env:
  browser: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:yml/standard"
  - "plugin:sonarjs/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:react/jsx-runtime"
  - "plugin:storybook/recommended"

parser: "@typescript-eslint/parser"

plugins:
  - sonarjs
  - react
  - react-hooks
  - "@typescript-eslint"

rules:
  no-useless-concat: error
  require-await: error
  "sonarjs/prefer-immediate-return": off
  "sonarjs/no-nested-template-literals": off
  react/prop-types: off
  react/self-closing-comp: warn
  react-hooks/exhaustive-deps:
    - warn
    - additionalHooks: useRecoilCallback
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/consistent-type-imports": warn
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-empty-interface":
    - warn
    - allowSingleExtends: true

overrides:
  - files:
      - "*.ts"
      - "*.tsx"
    rules:
      no-undef: off
  - files:
      - "*.yml"
      - "*.yaml"
    parser: yaml-eslint-parser

settings:
  react:
    version: detect
